name: CI v2

on:
  workflow_dispatch:
    inputs:
      firmware_version:
        description: 'Firmware Version'
        required: true
        default: '23.05.3'
        type: choice
        options:
          - 23.05.3
          - 23.05.2
          - 23.05.1
      model_parameter:
        description: 'Parameters (visit readme)'
        required: true
        default: 'xiaomi_mi-router-3g, ramips/mt7621'
        type: string
      upload_all:
        description: 'Upload All Artifacts'
        required: false
        default: true
        type: boolean
      release:
        description: 'Create Release'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VENDOR: immortalwrt
      VERSION: ${{ github.event.inputs.firmware_version }}
      DATE: $(date +%Y-%m-%d)
      DATETIME: $(date +%Y-%m-%d_%H-%M-%S) # 添加 DATETIME 环境变量

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialization Environment
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip qemu-utils mkisofs jq

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 # 或者你所需的Python版本

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r build/requirements.txt # 如果有依赖文件，则安装依赖
      
      - name: 下载解压
        run: |
            python build/imagebuilder.py "${{ github.event.inputs.model_parameter }}"
        env:
          FIRMWARE_VERSION: ${{ github.event.inputs.firmware_version }}

      - name: 切换工作目录
        run: |
          cd ${{ env.VENDOR }}-imagebuilder-*/
          python ../build/building_image.py "${{ github.event.inputs.model_parameter }}"

      
            
      - name: Upload All Artifacts
        if: ${{ github.event.inputs.upload_all == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: firmware-artifacts
          path: |
            immortalwrt-imagebuilder-*/bin/targets/*/-*-squashfs-sysupgrade.bin
            immortalwrt-imagebuilder-*/bin/targets/*/-*-squashfs-factory.bin

