name: CI

on:
  workflow_dispatch:
    inputs:
      firmware_version:
        description: 'Firmware Version'
        required: true
        default: '23.05.3'
        type: choice
        options:
          - 23.05.3
          - 23.05.2
          - 23.05.1
      target_platform:
        description: 'Target Platform (visit https://example.com/platforms for valid options)'
        required: true
        default: 'PlatformExample'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 # 或者你所需的Python版本

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # 假设你有一个requirements.txt文件列出依赖项

      - name: Run Python Script
        run: |
          python app.py
        env:
          FIRMWARE_VERSION: ${{ github.event.inputs.firmware_version }}
          TARGET_PLATFORM: ${{ github.event.inputs.target_platform }}